### ISSUE TITLE
安卓p，我就看看，支持一下

### ISSUE THREAD

**Issue by idelin** [pengwei1024/12306XposedPlugin#1]
rt

**Comment by pengwei1024** [comment]
可惜我没有9.0设备。![](https://ws1.sinaimg.cn/large/9150e4e5gy1fy9fpsdvz5g208c08c0tj.gif)

**Comment by idelin** [comment]
> 可惜我没有9.0设备。![](https://camo.githubusercontent.com/4fc6b87f853277dac81433544bd0f4a18bef243e/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f393135306534653567793166793966707364767a35673230386330386330746a2e676966)
有没考虑支持太极，如果没什么黑科技估计是直接支持的？

**Comment by idelin** [comment]
> 可惜我没有9.0设备。![](https://camo.githubusercontent.com/4fc6b87f853277dac81433544bd0f4a18bef243e/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f393135306534653567793166793966707364767a35673230386330386330746a2e676966)

有没考虑支持太极，如果没什么黑科技估计是直接支持的？

**Comment by pengwei1024** [comment]
> > 可惜我没有9.0设备。![](https://camo.githubusercontent.com/4fc6b87f853277dac81433544bd0f4a18bef243e/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f393135306534653567793166793966707364767a35673230386330386330746a2e676966)
> 
> 有没考虑支持太极，如果没什么黑科技估计是直接支持的？

太极目前不支持安装12306吧？之前试过VirtualXposed，这个运行12306提交订单一直服务器返回签名错误，试了很多方法也没有解决

**Comment by starlightjy** [comment]
> > > 可惜我没有9.0设备。![](https://camo.githubusercontent.com/4fc6b87f853277dac81433544bd0f4a18bef243e/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f393135306534653567793166793966707364767a35673230386330386330746a2e676966)
> > 
> > 
> > 有没考虑支持太极，如果没什么黑科技估计是直接支持的？
> 
> 太极目前不支持安装12306吧？之前试过VirtualXposed，这个运行12306提交订单一直服务器返回签名错误，试了很多方法也没有解决

最新的太极5.0.1已经支持创建第三方应用了,我试了12306可以创建.可以考虑跟进一下不?

**Comment by pengwei1024** [comment]
> > > > 可惜我没有9.0设备。![](https://camo.githubusercontent.com/4fc6b87f853277dac81433544bd0f4a18bef243e/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f393135306534653567793166793966707364767a35673230386330386330746a2e676966)
> > > 
> > > 
> > > 有没考虑支持太极，如果没什么黑科技估计是直接支持的？
> > 
> > 
> > 太极目前不支持安装12306吧？之前试过VirtualXposed，这个运行12306提交订单一直服务器返回签名错误，试了很多方法也没有解决
> 
> 最新的太极5.0.1已经支持创建第三方应用了,我试了12306可以创建.可以考虑跟进一下不?

可以啊，抽空我试试能不能成功提交订单

**Comment by pengwei1024** [comment]
> rt

话说Android P需要适配什么呀？我在模拟器上9.0跑了下没有什么问题呀

**Comment by idelin** [comment]
> > rt
> 
> 话说Android P需要适配什么呀？我在模拟器上9.0跑了下没有什么问题呀

要太极支持的话要开发者去太极那申请支持才可以，太极对xposed软件有个白名单好像，白名单之外不能使用
